Feature/ad 51 admin verify new users
Legal-Innovation-Lab-Wales/agor-dawn pull request #31
Opened 2021-09-16 09:54 UTC by AlexW555

This PR adds in the ability for admins to verify new user signups via the admin page. There are also some smaller additional changes added in for this branch, to ensure it functions for production testing:

- New Users have to login/signup to access the system
- Added in toggle boolean to user-field for approval
- Emails to admins when new users signup
- Removed search bar for non-signed in users
- Updated environments for email sending

<img width="1433" alt="Screenshot 2021-09-16 at 10 48 20 am" src="https://user-images.githubusercontent.com/17786854/133590773-8b0b5336-bf1c-452e-9eba-c23125edfe4f.png">

<img width="1434" alt="Screenshot 2021-09-16 at 10 38 10 am" src="https://user-images.githubusercontent.com/17786854/133590515-28704f08-2251-46eb-a30e-d455b054b6b4.png">

<img width="1431" alt="Screenshot 2021-09-16 at 10 39 15 am" src="https://user-images.githubusercontent.com/17786854/133590536-19ad4b4d-db1b-4489-abd7-45bb56f3893d.png">

Note: There is a known bug with the restricting access to signup simular to that of include journey where the flash notice won't appear.

 `def require_approval 
return unless current_user && !current_user.approved?
    flash[:notice] = "You require approval to use the system"
    sign_out_and_redirect(current_user)
  end`

2021-09-17 06:44 UTC, phil-6 commented
I don't think "authenticated" is the right word for the UI. Authenticated usually refers to signed in or not. Could we change the wording to Approved please?

I also don't think we need to display the section if there are no users waiting approval

2021-09-17 10:47 UTC, IeuanSkinner commented
@AlexW555 we discussed admins only being able to promote other users to admin but not demote them because of all the issues that could arise from that but this has gone unimplemented.

2021-09-17 10:51 UTC, IeuanSkinner commented on app/controllers/admin_controller.rb
> +    @unauthenticated_users = User.all.where(approved: false)
This should be a scope on the user model.

2021-09-17 10:51 UTC, IeuanSkinner commented on app/views/admin/index.html.erb
> +    <% @users.each do |user| %>
This isn't just showing "Authenticated" users, it's showing all users.

2021-09-17 10:55 UTC, IeuanSkinner commented
**All** of the platforms users are currently appearing in a large single table on that screen so as the number of users on the platform increases so too will the size and time taken to render that screen until it becomes a problem.

2021-09-17 10:56 UTC, IeuanSkinner commented
More consideration is needed for the mobile view, currently the table will overflow creating a horizontal scroll and blank space to the right of the toolbar:

<img width="450" alt="Screenshot 2021-09-17 at 11 53 51" src="https://user-images.githubusercontent.com/6815945/133771605-73dc08b1-9a31-4530-859f-810452d0f829.png">

2021-09-17 11:12 UTC, IeuanSkinner commented on app/views/admin/index.html.erb
> +    <% else %>
Indentation is off here, the else statement isn't aligning with the corresponding if and the inner p tag is indented fewer times than the parent else.

2021-09-17 11:13 UTC, garethdandrews commented
> More consideration is needed for the mobile view, currently the table will overflow creating a horizontal scroll and blank space to the right of the toolbar:
> 
@IeuanSkinner I believe I have resolved this issue on my branch.

2021-09-17 11:14 UTC, IeuanSkinner commented on app/views/devise/sessions/new.html.erb
> +    <p>Note: This is a closed platform. If you have signed up, you must wait for an admin to approve your signup before
This should be styled to be more apparent.

2021-09-17 11:15 UTC, IeuanSkinner commented on app/views/shared/_navbar.html.erb
> +    <% if !current_user.nil? %>
This should be `unless current_user.nil?`, does your IDE not highlight this?

2021-09-17 11:15 UTC, IeuanSkinner commented on config/environments/development.rb
> +  # Tell Active Support which deprecation messages to disallowconfig.active_support.disallowed_deprecation_warnings = []
What's occurred here?

2021-09-17 11:18 UTC, IeuanSkinner commented on app/models/user.rb
> +  after_create :mail_admins, if: -> { !approved? }
In hindsight his would actually be better as `unless: -> { approved? }`

2021-09-17 11:19 UTC, IeuanSkinner commented on app/views/admin/index.html.erb
> +  <h2>Unauthenticated Users</h2>
I'd place this in the if statement and delete the else, we don't need to show anything if there are no unapproved users.

2021-09-17 11:23 UTC, IeuanSkinner commented on app/controllers/application_controller.rb
> +    flash[:notice] = "You require approval to use the system"
This doesn't do anything so can be removed.

2021-09-17 11:31 UTC, IeuanSkinner commented
The routing is kind of odd in this platform now, you've stuck an `authenticate_user!` before action onto the application controller which *will* work but it means in theory a route could be added to a controller not extending the application controller or a controller could just call `skip_before_action` and we'd have routes into the platform that are accessible by unauthenticated users which we no longer want.

We typically handle this at the routing layer and so wrapping all of our resource endpoints in an authenticated block and having an unauthenticated block that redirects to sign in (see: Dragon Spotter), this way if somebody did try to add such an endpoint it would be identifiable from the routes file.

2021-09-17 11:32 UTC, IeuanSkinner commented on app/controllers/admin_controller.rb
> +  end
Should a user be emailed once they've been approved by an admin?

2021-09-17 11:35 UTC, IeuanSkinner commented on app/controllers/admin_controller.rb
> +    redirect_to root_path, flash: { error: 'You do not have access to this page ' } unless current_user.admin
You can use `redirect_back` here with the fallback being the root path, I'd also not opt for a flash message as you don't want to indicate to somebody who is prying for vulnertabilities that such a path exists.

2021-09-17 11:36 UTC, IeuanSkinner commented on app/mailers/application_mailer.rb
> +  default from: 'agor-dawn-demo@legaltech.wales'
The platform domain is `agordawn.legaltech.wales` so I think `agordawn@legaltech.wales` would fit better.

2021-09-17 11:43 UTC, IeuanSkinner commented on app/mailers/admin_mailer.rb
> +    mail(to: @admin.email, subject: 'New User Signup', body: 'A new user has signed up, sign in to approve them https://agordawn.legaltech.wales/admin')
Do not use absolute URLs to platform routes! You can access this route using `"A new user has signed up, sign in to approve them #{admin_index_url}"` **however** this link needs to be interpreted as an HTML link not just plaintext.

Also more information should definitely be given to the admin here such as the users name/email address otherwise what is the point of passing the user object?

2021-09-17 11:44 UTC, IeuanSkinner commented on app/views/pages/home.html.erb
> +    <div class="container search-browse">
This indentation is now misaligned 🤨

2021-09-20 10:39 UTC, IeuanSkinner commented on app/controllers/admin_controller.rb
> +    UserMailer.new_verify(@user)
Logically this makes more sense as a `before_update` callback listener on the user model where the approved attribute changes from false to true.

2021-09-20 10:40 UTC, IeuanSkinner commented on app/mailers/user_mailer.rb
> +  def new_verify(user)
Why `new_verify`? How about `approved` so the call reads as `UserMailer.approved(user)`?

2021-09-20 14:38 UTC, IeuanSkinner commented on app/views/shared/_navbar.html.erb
> +    <%=  render 'shared/search'  %>
The indentation is off here, if you have a set of tags then the content within those tags should be indented by a level.

```
<tag>
    I am indented!
</tag>
```

2021-09-20 14:44 UTC, IeuanSkinner commented on app/models/user.rb
> +    UserMailer.approved(self).deliver_now if :approved == true && saved_change_to_approved?
This if statement can be applied to the callback listener i.e.

`before_update :mail_user, if: -> { approved? && saved_change_to_approved? }`

2021-09-20 14:44 UTC, IeuanSkinner commented on app/mailers/user_mailer.rb
> +end
Missing newline at the end of file, does your IDE highlight this?

2021-09-20 14:57 UTC, AlexW555 commented on app/mailers/user_mailer.rb
> +end
Yes, I just missed this at the end of the file

2021-09-20 14:59 UTC, IeuanSkinner commented on app/models/user.rb
> +    UserMailer.approved(self).deliver_now if :approved == true && saved_change_to_approved?
Also this doesn't appear to work at all, `saved_change_to_approved?` will be false in the `before_update` context but true when `after_update` is called.

If we change it to use `after_update` then it's possible to approve the user without them receiving an email as the DB transaction will commit before the listener runs. If we want to prevent that and keep `before_update` then the best bet it to use `approved_was` in conjunction with `approved`.

2021-09-20 15:04 UTC, AlexW555 commented on app/models/user.rb
> +    UserMailer.approved(self).deliver_now if :approved == true && saved_change_to_approved?
Literally, what I was about to write. Tested it and it seems that before_update it would always be false 😅

2021-09-20 15:05 UTC, AlexW555 commented on app/models/user.rb
> +    UserMailer.approved(self).deliver_now if :approved == true && saved_change_to_approved?
Going to try your solution now

2021-09-20 15:16 UTC, AlexW555 commented on app/models/user.rb
> +    UserMailer.approved(self).deliver_now if :approved == true && saved_change_to_approved?
I'm guessing there is something wrong in how I am formatting it?
<img width="1023" alt="Screenshot 2021-09-20 at 4 12 51 pm" src="https://user-images.githubusercontent.com/17786854/134027052-91f31a0e-81a8-435c-825f-c18ab771d8ce.png">

2021-09-20 15:19 UTC, AlexW555 commented on app/controllers/admin_controller.rb
> +    UserMailer.new_verify(@user)
Removed from here and added as a callback listener on user model

2021-09-20 15:25 UTC, IeuanSkinner commented on app/models/user.rb
> +    UserMailer.approved(self).deliver_now if :approved == true && saved_change_to_approved?
`approved_was` doesn't take an argument, it returns the previous value of the approved attribute.

2021-09-22 08:34 UTC, AlexW555 commented
All PR Changes are now implemented

2021-09-22 08:43 UTC, AlexW555 commented
> > More consideration is needed for the mobile view, currently the table will overflow creating a horizontal scroll and blank space to the right of the toolbar:
> 
> @IeuanSkinner I believe I have resolved this issue on my branch.

Will bring in Format fixes on Gareths branch when he merges to main his work, As his branch changes structure and naming of some the items in the stylesheets and html.erb files.

2021-09-22 13:52 UTC, IeuanSkinner commented on app/models/user.rb
> +  before_update :mail_user, if: -> { !approved_was() && approved? }
Does your IDE not highlight this? You don't need parentheses when doing a no-arg method call in Ruby.

![Screenshot 2021-09-22 at 14 51 59](https://user-images.githubusercontent.com/6815945/134356575-45d75203-460e-496d-971b-9294ebd5f850.png)

2021-09-22 16:05 UTC, AlexW555 commented on app/models/user.rb
> +  before_update :mail_user, if: -> { !approved_was() && approved? }
Apologies, I did see it but it was highlighted first as 'Cannot find approved_was'

2021-09-23 08:29 UTC, IeuanSkinner commented
### Security Bug

So I spotted in the admin controller that a `before_action` of authorize admin was occuring only on the index action of the controller, in the below video I show why this is a security bug.

In this video I am logged in at as test-user-1 whose user ID I can find by visiting my own profile. I then execute a JS fetch request to endpoint `/admin/users/:my_id` of method `put` including the embedded CSRF Token in the headers and I am now an admin user.

https://user-images.githubusercontent.com/6815945/134476479-03712358-2ba7-4c84-a6e2-1f160a3586f4.mov

2021-09-23 08:33 UTC, IeuanSkinner commented on app/controllers/admin_controller.rb
>    before_action :authorize_admin, only: :index
There is no action named `index` hence why the IDE highlights this.

![Screenshot 2021-09-23 at 09 32 47](https://user-images.githubusercontent.com/6815945/134476993-e624dace-b90a-4988-8071-ec5af2bd0245.png)

2021-09-23 08:36 UTC, IeuanSkinner commented on app/controllers/admin_controller.rb
`# GET /user/admin` is not a valid route so the show action should not be annotated with it. (The show action should not exist at all, you've specified in the routes file that only the index action should be included for admin resource.

2021-09-23 08:43 UTC, IeuanSkinner commented on app/controllers/admin_controller.rb
> +  def reject
This can be a lot DRY-er

```
  # PUT /admin/users/:id/reject
  def reject
    return if @user.approved

    flash[:success] = "#{@user.full_name} has been rejected" if @user.destroy
    flash[:error] = "#{@user.full_name} couldn't be rejected" unless flash[:success].present?

    redirect_back(fallback_location: admin_index_path)
  end
```

2021-09-23 08:57 UTC, IeuanSkinner commented on app/controllers/admin_controller.rb
>    def toggle_admin
Why is the toggle admin route the base route whereas approval/rejection are their own routes? It seem to me we the `toggle_admin` (which should really be called `make_admin`) action should be mapped to `/admin/users/:id/admin`

2021-09-23 09:20 UTC, IeuanSkinner commented on config/routes.rb
> +      put 'reject', action: 'reject', on: :member, as: :reject
So you've annotated the actions as `/admin/users/:id/(approve/reject)` to mirror what the `toggle_admin` action is doing but this routes config isn't producing that route at all.

![Screenshot 2021-09-23 at 10 13 15](https://user-images.githubusercontent.com
/6815945/134482286-c8bd4fbd-888a-48c2-9860-9dc97f19a8b6.png)

You can achieve these routes by doing this instead:
```
    resources :admin, only: :index

    scope 'admin/users/:id', constraints: { id: /\d+/ }, controller: 'admin' do
      put '/', action: 'toggle_admin', as: :toggle
      put '/approve', action: 'approve', as: :approve
      put '/reject', action: 'reject', as: :reject
    end
```

![Screenshot 2021-09-23 at 10 19 57](https://user-images.githubusercontent.com/6815945/134483075-4c9768a3-864a-43a4-ba70-37349cbec5dc.png)

2021-09-23 09:27 UTC, IeuanSkinner commented on db/migrate/20210719145858_devise_create_users.rb
> +      t.boolean   :approved, default: false
This allows for a `NULL` approved state does it not? Should it not be `t.boolean :approved, null: false, default: false`?

2021-09-23 10:50 UTC, AlexW555 commented
> ### Security Bug
> So I spotted in the admin controller that a `before_action` of authorize admin was occuring only on the index action of the controller, in the below video I show why this is a security bug.
> 
> In this video I am logged in at as test-user-1 whose user ID I can find by visiting my own profile. I then execute a JS fetch request to endpoint `/admin/users/:my_id` of method `put` including the embedded CSRF Token in the headers and I am now an admin user.
> 
>  Screen.Recording.2021-09-23.at.09.21.38.mov

I removed the before_action only occurring for index. I get the same result as you demonstrated but no admin update on refresh. I can't tell from the video, are you refreshing the page once the script is run or is this now correct behavior?

https://user-images.githubusercontent.com/17786854/134494374-34e70a6d-7683-4238-a816-1f260bb5abe6.mov

2021-09-27 10:29 UTC, IeuanSkinner commented
@AlexW555 you've misunderstood what's occurring, you're seeing a 302 because the result of `authorize_admin` is a `redirect_back`, the fact that the user is no longer becoming an admin, which can be checked by:

- including debugger in `make_admin` action that will not be hit
- checking the user model in rails console

means that the `authorize_admin` action is now safeguarding against any non-admins from calling this action. 

Worth noting it's probably best to stick this as the highest order `before_action` in the controller to prevent any other code from evaluating that won't need to.

2021-09-27 15:54 UTC, phil-6 requested changes
Added some comments througout.
Main work is on refactoring usages of "authenticated" to "authorised". They don't have the same meaning.

I've also posed some questions and suggested some other changes. 

Should an approved user be able to be rejected. What happens if an Admin clicks "approve" by mistake? What options does an Admin have at present for "banning" a user?
I'm a BIG fan of [Neilsen's Usability Heuristics](https://www.nngroup.com/articles/ten-usability-heuristics/) #3 is about allowing users to make mistakes and supporting undo and redo.

This is good progress so far Alex but I think there is still quite a lot of work to do.

2021-09-27 15:54 UTC, phil-6 commented on app/controllers/admin_controller.rb
> +    redirect_back(fallback_location: admin_index_path, flash: { success: "#{@user.full_name} is now approved" })
What are the differences between `redirect_back` and `redirect`? 
What does `fallback_location` actually mean?

2021-09-27 15:54 UTC, phil-6 commented on app/controllers/application_controller.rb
> +    sign_out_and_redirect(current_user)
Are we displaying any message to the users here?
Could we redirect them to a custom error page which explains what's happened and what they can do to fix the error?

2021-09-27 15:54 UTC, phil-6 commented on app/models/user.rb
> +  before_update :mail_user, if: -> { !approved_was && approved? }
This seems quite complicated. "If not approved_was and is appproved"
Would it make more sense to have the mail user function as an after_action on the admin approve user method?
`mail_user` is also too generic a function name.

I would suggest adding `mail_approved_user` and `mail_rejected_user` as after actions in the admin controller. 

@IeuanSkinner How do you feel about that proposal?

2021-09-27 15:54 UTC, phil-6 commented on app/views/admin/index.html.erb
> +      <% @unauthenticated_users.each do |user| %>
I'm still not happy with using "unauthenticated" here, We mean "unapproved".

2021-09-27 15:54 UTC, phil-6 commented on app/views/admin/index.html.erb
> +    <% @authenticated_users.each do |user| %>
as above, please refactor this to "@approved_users"

2021-09-27 15:54 UTC, phil-6 commented on app/controllers/admin_controller.rb
> +    @authenticated_users = User.authenticated.order(:first_name)
Please can we refactor these to approved/unapproved.
Authenticated indicates log in/out. Which is not correct in this context

2021-09-27 15:54 UTC, phil-6 commented on app/models/user.rb
> +  scope :authenticated, -> { where(approved: true) }
I don't like the mixed naming here.

2021-09-27 15:54 UTC, phil-6 commented on app/views/devise/sessions/new.html.erb
> +    </div>
Do you think it would be a better experience to have this as a custom error page?
The HTTP 401 error code is specifically "Unauthorised" we could throw this error and redirect to an 401 error page.

2021-09-27 15:54 UTC, phil-6 commented on config/routes.rb
> +    scope 'admin/users/:id', constraints: { id: /\d+/ }, controller: 'admin' do
Do we need the constraints here?
If so why?

(this might also be a question for @IeuanSkinner, but Alex, please see if you can find the answer first!)

2021-09-27 15:54 UTC, phil-6 commented on config/routes.rb
> +      put '/', action: 'make_admin', as: :make_admin
This seems odd to me that it's a put on '/'. Please can you explain this.

2021-09-27 15:54 UTC, phil-6 commented on config/routes.rb
> +  end
Does this flash any messages?

2021-09-27 15:54 UTC, phil-6 commented on app/controllers/admin_controller.rb
> +  # PUT /admin/users/:id/admin
I don't think this matches up with the route.

2021-09-27 15:54 UTC, phil-6 commented on app/controllers/admin_controller.rb
> +
Is there a way to remove a User's admin status. User actions should be reversible, especially on something like awarding admin privileges.

2021-09-27 15:54 UTC, phil-6 commented on app/controllers/admin_controller.rb
> +    return if @user.approved
Does this mean that a user cannot be rejected once they've been approved?

2021-09-28 09:20 UTC, AlexW555 commented on app/controllers/admin_controller.rb
> +    redirect_back(fallback_location: admin_index_path, flash: { success: "#{@user.full_name} is now approved" })
redirect_back added in rails 5 directs the browser back to the page that issued the request. Otherwise it redirects back to the provided fallback_location. This would be useful if we wanted this action to be referred to from different pages. 

In relation to this project, I can't think of any other locations we might want to refer to this action other than the admin page. So this can be a simple redirect.

2021-09-28 10:10 UTC, AlexW555 commented on app/controllers/application_controller.rb
> +    sign_out_and_redirect(current_user)
What can they really do to fix the error? I don't think a custom error page is needed as the information they really need is on the login page. "This is a closed platform. If you have signed up, you must wait for an admin to approve your account before you can login." 

I could add a modal popup for a "Help" which could contain: 
"If you believe this to be an error please contact an admin" and a reminder "You will get an email when your approved"?

2021-09-28 10:28 UTC, AlexW555 commented on config/routes.rb
> +  end
Added in flash message

2021-09-28 10:34 UTC, AlexW555 commented on app/controllers/admin_controller.rb
> +
Currently we only have admins and users. So should admins be able to demote other admins?

I get your point, so adding in a confirmation step to make sure the admins can be sure they know the consequences would be hugely beneficial.

The potential solution option is an undo option, But I feel would this add a lot of complexity?

2021-09-28 10:53 UTC, AlexW555 commented on config/routes.rb
> +      put '/', action: 'make_admin', as: :make_admin
Changed to '/make_admin'

2021-09-28 10:54 UTC, AlexW555 commented on app/controllers/admin_controller.rb
> +  # PUT /admin/users/:id/admin
Updated to reflect new route path `'# PUT /admin/users/:id/make_admin'`

2021-09-28 12:37 UTC, AlexW555 commented on app/controllers/application_controller.rb
> +    sign_out_and_redirect(current_user)
I've added in a flash as this gets triggered when an un-approved user tries to sign in

`flash[:error] = "You require approval from an admin before you can sign in."`

![Screenshot 2021-09-28 at 1 33 41 pm](https://user-images.githubusercontent.com/17786854/135087684-10f7aeb7-c536-40b9-a82e-8728fd1bc863.png)

2021-09-28 12:53 UTC, AlexW555 commented on config/routes.rb
> +    scope 'admin/users/:id', constraints: { id: /\d+/ }, controller: 'admin' do
I believe we do need them here as it's restricting id's to only be integers. Preventing anything like `admin/users/abc`. I thought this would be something rails would do naturally.

You can't naturally navigate to admin/users/3 or admin/users/:id/make_admin but I'm guessing this is protecting some sort of injection attack?

2021-09-28 12:56 UTC, AlexW555 commented on app/controllers/admin_controller.rb
> +    return if @user.approved
Yes, unapproved users are either approved/rejected.

2021-09-28 13:12 UTC, phil-6 commented on app/controllers/admin_controller.rb
> +
> So should admins be able to demote other admins?

Yes, I think so. @garethdandrews what do you think?

2021-09-28 13:13 UTC, phil-6 commented on app/models/user.rb
> +  before_update :mail_user, if: -> { !approved_was && approved? }
I should have also tagged @garethdandrews here too.

2021-09-28 13:16 UTC, phil-6 commented on app/controllers/application_controller.rb
> +    sign_out_and_redirect(current_user)
> "This is a closed platform. If you have signed up, you must wait for an admin to approve your account before you can login."

Do we display this all of the time? Or just after an unapproved user attempts to login?

2021-09-28 13:18 UTC, AlexW555 commented on app/controllers/admin_controller.rb
> +
Added in confirmations for actions on the admin page. 

https://user-images.githubusercontent.com/17786854/135093903-6df5d931-66e0-476d-929f-941802d2ae7c.mov

2021-09-28 13:51 UTC, AlexW555 commented on app/controllers/admin_controller.rb
> +    return if @user.approved
_Can an approved user be rejected later?_
Not at this current stage. An approved user could be rejected later if It was incorporated to a feature to demote users out of the system rather than deleting their accounts. This could save a lot of database hits and could be an option incorporated in. 

But I don't think it comes under the scope of admins verifying new users. Currently reject is set to just remove that record from the database (It's a small database action as the user wouldn't have any related projects, comments at the time)

I think its useful and could be another feature ticket I would be happy to work on. It would include adding in another row to the admin view that provides temporary suspension action, along with the option to add reasoning why the user is not approved. As it would address rejecting an active user without explanation.

_What happens if a user is approved by mistake? Coming back to Neilsen's #3._
Similar to the earlier comment I have added in a confirmation stage now to explain to the admins what they are doing.  I think incorperating undo buttons is do-able but I'm again not sure how complex that would get if we are having to catch or queue actions. Do we want this?

_What if a user who was correctly approved but then does something which makes an admin want to reject them?_
I can see this coming up as a point from the result of the flag system too. I think a ticket like I mentioned above could be useful with temporary suspensions. What do you think?

2021-09-28 15:58 UTC, phil-6 commented on app/controllers/application_controller.rb
> +    sign_out_and_redirect(current_user)
Is that the best UX? Do we need to tell users that its a closed platform every time they sign in? Or is it something we should only tell users when they try and login before they are approved?
Question for you and @garethdandrews

2021-09-28 16:01 UTC, phil-6 commented on app/models/user.rb
> +  before_update :mail_user, if: -> { !approved_was && approved? }
>  In theory it could be the case that multiple controllers are capable of flipping this or a sysadmin might even do this via rails console and in those cases the user should be informed by an email which would get triggered because of the callback listener.

Good Point, well made.

I also prefer testing two positives. 

@AlexW555 does this make sense to you? Are you happy to implement and test this works that way around?

2021-09-28 16:10 UTC, phil-6 commented on app/controllers/admin_controller.rb
> +
Love it, looking really good.

Thoughts from you and @garethdandrews on reversibility of actions? As in demote from admin and reject after approval?

2021-09-28 16:10 UTC, phil-6 commented on app/controllers/admin_controller.rb
> +
Love it, looking real good!

2021-09-28 16:12 UTC, phil-6 commented on app/controllers/admin_controller.rb
> +    return if @user.approved
> But I don't think it comes under the scope of admins verifying new users

Very valid point, well made.
I agree, can be spun out of this into another ticket for future work and discussion. (Please can you do this)

2021-09-28 16:39 UTC, IeuanSkinner commented
> Should an approved user be able to be rejected. What happens if an Admin clicks "approve" by mistake? What options does an Admin have at present for "banning" a user?
> I'm a BIG fan of Neilsen's Usability Heuristics #3 is about allowing users to make mistakes and supporting undo and redo.

@phil-6 This is an interesting point, the problem with allowing approved users to be rejected is a question of access controls i.e. if admin A approved someone should admin B be able to then reject them, if not and it's only admin A do we need to track 'approved_by' on the User model and should they only be able to undo and reject them within X minutes of them being approved or could they bring out the reject ban-hammer at any point? 

If we allow all admins to make these actions then what stops an admin going rogue and rejecting every user? This is the same problem we have with being able to demote admin status and why we don't have a UI control for it.

The answer to "what do they do" ultimately is "contact the sysadmin" who is considered the superuser of everything and can remove Users, Profiles, Comments, Admin Status etc by adjusting the DB records (or using Rails console).

2021-09-28 17:04 UTC, IeuanSkinner commented on app/controllers/admin_controller.rb
>      @user = User.find(params[:id])
I've only just spotted this, so `make_admin` is setting up the user exactly as the approve and reject actions do and so this is repeating code that's not needed. In the case of this controller the user action can be called before all the other actions.

2021-09-29 09:46 UTC, AlexW555 commented on app/controllers/admin_controller.rb
> +    return if @user.approved
Added it [AD-59](https://lilw.atlassian.net/browse/AD-59?atlOrigin=eyJpIjoiNjI3ZWE2NmQ4ZTRiNDEwM2E2ZjEzYWNlNzQ5OGY2NWUiLCJwIjoiaiJ9)

2021-09-29 09:59 UTC, AlexW555 commented on app/models/user.rb
> +  before_update :mail_user, if: -> { !approved_was && approved? }
Changes made and tested to make sure it works. Do we want to be sending an email to rejected users too? If so what would be said?

`"#{user.full_name} your signup has not been approved. You can sign up again here #{root_url}")` ?

2021-09-29 10:24 UTC, AlexW555 commented on app/controllers/application_controller.rb
> +    sign_out_and_redirect(current_user)
Changes made. Thoughts?


<img width="1432" alt="Screenshot 2021-09-29 at 11 22 59 am" src="https://user-images.githubusercontent.com/17786854/135251028-e6b5ef74-c4fa-4636-af63-c4825d69a9f9.png">

2021-09-29 10:38 UTC, phil-6 commented on app/controllers/application_controller.rb
> +    sign_out_and_redirect(current_user)
Looks better to me. Good work Alex!

2021-09-29 10:39 UTC, phil-6 commented on app/models/user.rb
> +  before_update :mail_user, if: -> { !approved_was && approved? }
I would suggest we should email them but with something along the lines of:
Your sign up request has been rejected, please contact the team at email@email.com for further information"

2021-09-29 10:59 UTC, AlexW555 commented on app/controllers/admin_controller.rb
>      @user = User.find(params[:id])
I have made the changes and I have ended up with `before_action :user, only: %i[approve reject make_admin]`

Which to me doesn't sound ideal as `before_action :user` should work. But I get "Couldn't find User without an ID"

2021-09-29 11:01 UTC, AlexW555 commented on app/controllers/admin_controller.rb
> +    redirect_back(fallback_location: admin_index_path, flash: { success: "#{@user.full_name} is now approved" })
Changed to redirect_to

2021-09-29 11:21 UTC, IeuanSkinner commented on app/controllers/admin_controller.rb
> +    redirect_back(fallback_location: admin_index_path, flash: { success: "#{@user.full_name} is now approved" })
Why use `redirect_to`? If we know the action should return the user to the screen from which it was triggered then we should use `redirect_back` otherwise if we change the route of the screen from which the action happens or add an additional place from which the action can be called suddenly we'd have adverse behaviour 🤨

2021-09-29 11:28 UTC, IeuanSkinner commented on app/controllers/admin_controller.rb
>      @user = User.find(params[:id])
1. If every action calls user then you don't need to restrict that action using the only keyword.
2. I've checked out the branch and tried promoting an admin and it does work 🤔

2021-09-29 13:02 UTC, AlexW555 commented on app/models/user.rb
> +  before_update :mail_user, if: -> { !approved_was && approved? }
Added in, changed it to "please contact our team for further information" I'm not sure what email we would like to direct to at this stage.

2021-09-29 13:04 UTC, AlexW555 commented on app/views/devise/sessions/new.html.erb
> +    </div>
Removed this text and added as flash message

2021-09-29 13:53 UTC, AlexW555 commented on app/controllers/admin_controller.rb
>      @user = User.find(params[:id])
Removed the `only: %i[approve reject make_admin]`and added in an `exeption: index` so that the admin page can load.

2021-09-29 14:16 UTC, AlexW555 commented on app/controllers/admin_controller.rb
> +    redirect_back(fallback_location: admin_index_path, flash: { success: "#{@user.full_name} is now approved" })
Reverted the changes back to redirect_back. My bad, I assumed this was a implied change too alongside the clarification

2021-09-30 13:12 UTC, IeuanSkinner commented on app/controllers/admin_controller.rb
> +  before_action :user, except: :index
Rails _will_ accomodate routing directly to the index template but our IDE's (is yours not doing this?) will complain when they see an action referenced without that action defined in the class.

<img width="381" alt="Screenshot 2021-09-30 at 14 10 37" src="https://user-images.githubusercontent.com/6815945/135461571-a32d501f-aab1-4bbc-b8ff-2d16af6a7421.png">

2021-09-30 13:13 UTC, IeuanSkinner commented on app/controllers/admin_controller.rb
> +    @user.update(approved: true)
This should be `update!` if we don't intend to handle any raised exceptions ourselves.

2021-09-30 13:20 UTC, IeuanSkinner commented on app/controllers/admin_controller.rb
> +    @approved_users = User.approved.order(:first_name)
You could update the user model to include:

`default_scope { order(first_name: :asc) }`

or if this ordering is only applicable to the users when they'e approved/unapproved scope then it can be added to those scopes 

```
scope :unapproved, -> { where(approved: false).order(first_name: :asc) }
scope :approved, -> { where(approved: true).order(first_name: :asc) }
```

2021-09-30 13:24 UTC, IeuanSkinner commented on app/mailers/user_mailer.rb
> +         body: "#{user.full_name} your signup request has been rejected. Please contact the team for further information")
Can we add a TODO comment in here that this needs more info on how to contact the admin team i.e. is there a specific email address or contact form on the site?

2021-09-30 13:27 UTC, phil-6 commented on app/controllers/admin_controller.rb
> +  before_action :user, except: :index
Do we need to worry about this? The index action is inherited, but the IDE doesn't know this hence the error.

2021-09-30 13:27 UTC, IeuanSkinner commented on app/views/admin/index.html.erb
> +          <% unless user.admin? %>
Ruby doesn't like using unless with else even though it technically works, again the IDE should be highlighting this for you?

![Screenshot 2021-09-30 at 14 25 13](https://user-images.githubusercontent.com/6815945/135463960-7f05fc1c-aed3-4371-90fa-31ded9d28106.png)

This is easy enough to convert into an if-else.

2021-09-30 13:28 UTC, phil-6 commented on app/controllers/admin_controller.rb
> +    @approved_users = User.approved.order(:first_name)
We've just discussed this one. The order would likely be extracted to a pagination function at some point, which would allow other sorting. With this in mind do you see the benefit of adding this to the scopes?

2021-09-30 13:34 UTC, phil-6 commented on app/mailers/admin_mailer.rb
> +         body: "A new user, #{user.full_name} has signed up with the email address #{user.email}. Sign in to approve them #{root_url}")
Yep, Alex was concerned about seeing routing errors for this path when unathenticated on localhost but redirect works on prod

2021-09-30 13:34 UTC, IeuanSkinner commented on app/controllers/application_controller.rb
> +    flash[:error] = "You require approval from an admin. Please wait for an admin to approve your account before you can log in"
It's really fastidious but you tend to miss the punctuation at the end of these error messages, [it's best practice to be gramatically correct throughout](https://docs.microsoft.com/en-us/dotnet/standard/exceptions/best-practices-for-exceptions?redirectedfrom=MSDN#use-grammatically-correct-error-messages) even with ending punctuation.

2021-09-30 13:36 UTC, IeuanSkinner commented on app/controllers/admin_controller.rb
> +  before_action :user, except: :index
I know that, I said as much in my comment, but you do not want a team of software developers to have "ignoring IDE warnings" to become an accepted/learned behaviour.

2021-09-30 13:37 UTC, phil-6 commented on app/controllers/application_controller.rb
> +    flash[:error] = "You require approval from an admin. Please wait for an admin to approve your account before you can log in"
Is it the right thing to do though?
https://www.independent.co.uk/life-style/full-stop-end-texting-rude-b1876131.html

2021-09-30 13:39 UTC, IeuanSkinner commented on app/controllers/application_controller.rb
> +    flash[:error] = "You require approval from an admin. Please wait for an admin to approve your account before you can log in"
The above also applies to the messaging in the mailers.

2021-09-30 13:40 UTC, phil-6 commented on app/controllers/admin_controller.rb
> +  before_action :user, except: :index
Agreed, would you just create an empty method then?

2021-09-30 13:45 UTC, IeuanSkinner commented on app/controllers/admin_controller.rb
> +    @approved_users = User.approved.order(:first_name)
Seems unlikely that you'd want to add that, in _Getting Real_ there's a principle about making decisions **for** a user and moving on. 

Choosing a default order at this point and then making the sorting change later if it becomes an absolute **must** for Agor seems more in-line with those principles than leaving repeat code in place just-in-case.

2021-09-30 13:46 UTC, IeuanSkinner commented on app/controllers/admin_controller.rb
> +  before_action :user, except: :index
No it's the classic just-does-a-render action:

```
def index
    render 'index'
end
```

2021-09-30 13:51 UTC, phil-6 commented on app/controllers/application_controller.rb
> +    flash[:error] = "You require approval from an admin. Please wait for an admin to approve your account before you can log in"
Mailers updated, flash alerts not updated yet... because I feel as though I'm too old to make the decision!

2021-09-30 14:03 UTC, IeuanSkinner commented on app/controllers/application_controller.rb
> +    flash[:error] = "You require approval from an admin. Please wait for an admin to approve your account before you can log in"
Are flash messages considered "casual context" though? They're meant to be informing the user of some action that was successful or not given their action. 🤔 

I must be old as well though as I'd never consider a full-stop rude. 🤷‍♂️

2021-10-01 10:14 UTC, merged